# Generated by Django 6.0.3 on 2026-04-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Баннер'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='banner_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='descriptions',
            field=models.TextField(default='я думал, но не придумал...', max_length=300, verbose_name='Описание профиля'),
        ),
    ]
